### ISSUE TITLE
[request] code snippet to retrieve files/data from local database

### ISSUE THREAD

**Issue by pzarabadip** [wolverton-research-group/qmpy#122]
Hi, 

First, thanks a lot for open-sourcing the code and database which I highly appreciate it. 

I have recently installed the database locally for faster query of the entries. However, I've had a bit of difficulty in retriveing structures from the database, and thought to ask here if it is possible to share a code snippet which would help solving my issue.

As an example, I would like to know if I follow the tutorial for getting the entries based on the composition as:
```python
elts = [ 'Fe', 'Li', 'O' ]
others = Element.objects.exclude(symbol__in=elts)
comps = Composition.objects.exclude(element_set=others)
```
How can I iterate over the composition and retrive the structures associated with each entry?

Best regards,
Pezhman

**Comment by tachyontraveler** [comment]
Hi @pzarabadip ! I hope you solved this problem yourself since you closed the Issue. Unfortunately, we don't have a dedicated support system for OQMD due to the limited resources available to us. But I'll try to get to such issues/requests when possible. Lmk if you still need any assistance in this regard.

**Comment by pzarabadip** [comment]
Hi @tachyontraveler 
Thanks a lot for following up on this issue.
I thought the issue tracker might be unmonitored and I sent off an email.

Unfortunately, I have not figured it the solution for this query. Your help would be much appreciated. 

I've also added the following query to the email:

```
Also, I am not sure if the local database also contains vasp input/output files? If yes, may you also let me know how can I access them through API?
```

**Comment by tachyontraveler** [comment]
1. To iterate over `Entry` objects associated with a given `Composition`, do something like this:
```
elts = [ 'Fe', 'Li', 'O' ]
others = Element.objects.exclude(symbol__in=elts)
comps = Composition.objects.exclude(element_set=others)
for comp in comps:
    entries = item.entries
    for ent in entries:
        pass       # insert your code to deal with Entry data here
```

Usage of either `comp.entries`  or  `comp.entry_set.filter()` should provide the same results.  The former one outputs a list of associated Entry objects. But in the latter one, you can even do extra filtering operations among the associated Entry objects via the `filter` function call.

**Comment by tachyontraveler** [comment]
As a tip in general, I'd recommend printing all the functions and variables associated with a  given _qmpy_ object to see your options.
For example, executing `print(dir(comps[0]))` would list all the methods and attributes of the `Composition` class object `comps[0]`. That list includes both `entries` and `entry_list`. 


To answer your question about raw files:
The raw files from VASP are not included in the SQL DB. But you can re-generate all the input and relevant output data from the SQL DB. We're actively looking into publishing the raw files, but the computational infrastructure currently in place for oqmd.org is unable to handle the significant amount of extra server load and traffic expected while providing raw files as well. 

PS: Just to be clear, the raw files are not maintained as private. The constraints on their open access arise only due to the limitations on our server resources.

**Comment by pzarabadip** [comment]
Thanks a lot @tachyontraveler, much appreciated. 
Best regards,
Pezhman

**Comment by jlaw9** [comment]
@pzarabadip Did you figure out how to extract the necessary info to reconstruct the structure files from the SQL DB? Could you please post your solution here?
